baseURL = "http://example.org/"

languageCode = "en"

title = "My New Hugo Site"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "sitemap"]

theme = "cdts.canada.ca"

defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 10
  [languages.fr]
    contentDir = "content/fr"
    languageName = "Fran√ßais"
    weight = 20